//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagementProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_permission
    {
        public int client_perm_id { get; set; }
        public int porduct_id { get; set; }
        public int client_id { get; set; }
        public System.DateTime permission_date { get; set; }
    
        public virtual client client { get; set; }
        public virtual product product { get; set; }
    }
}
