//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagementProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreSystemDBEntities : DbContext
    {
        public StoreSystemDBEntities()
            : base("name=StoreSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<client_permission> client_permission { get; set; }
        public virtual DbSet<move_product> move_product { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<supply_permission> supply_permission { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
