//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagementProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class move_product
    {
        public int move_id { get; set; }
        public int product_id { get; set; }
        public int from_store_id { get; set; }
        public int to_store_id { get; set; }
        public System.DateTime move_date { get; set; }
    
        public virtual product product { get; set; }
        public virtual store store { get; set; }
        public virtual store store1 { get; set; }
    }
}
