//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagementProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.supply_permission = new HashSet<supply_permission>();
        }
    
        public int supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_phone { get; set; }
        public string supplier_fax { get; set; }
        public string supplier_mobile { get; set; }
        public string supplier_emial { get; set; }
        public string supplier_website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supply_permission> supply_permission { get; set; }
    }
}
